### ISSUE TITLE
Force Quit

### ISSUE THREAD

**Issue by leolelego** [samscam/transmote#1]
Hello,

I would lim to use your app, i downloaded the compiled version, but the app is always blocked when I click on any buttons (on Sparkle buttons too). [Download the log file](http://cl.ly/0S0O3H13003R).

Your project looks like to be very interesting ! it support or will support (i can't run it so i don't know) Transmission groups ? (i use a lot of groups with 'Assign group to new transfert based criteria').

I really want to use your app, soon as possible 😊

**Comment by samscam** [comment]
Hello @leolelego 

Sorry it's not working for you, I will look into it properly.

Perhaps try this earlier version (and don't update it if it nags!): http://samscam.co.uk/transmote/release/Transmote-0.1.25.zip

S

**Comment by leolelego** [comment]
your problem look like to be associate with the OSX keychain access. I think ou do that in the main thread or the UI thread. Because the app loop only after i enter my password and id and after the keychain password verification.

**Comment by samscam** [comment]
Closing this. App has been completely re-written :)
